---
abstract: "Use Mouse's type constraints."
author:
  - 'Hideaki Ohno<hide.o.j55@gmail.com>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
keywords:
  - Mouse
  - FormValidator::Lite
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FormValidator-Lite-Constraint-Mouse
no_index:
  directory:
    - t
    - xt
    - inc
    - eg
provides:
  FormValidator::Lite::Constraint::Mouse:
    file: lib/FormValidator/Lite/Constraint/Mouse.pm
    version: 0.03
requires:
  FormValidator::Lite: 0.10
  Mouse: 0.90
  Mouse::Util::TypeConstraints: 0
  perl: 5.008003
resources:
  bugtracker: https://github.com/hideo55/FormValidator-Lite-Constraint-Mouse/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/FormValidator-Lite-Constraint-Mouse.git
version: 0.03
