---
abstract: "Use Mouse's type constraints."
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FormValidator-Lite-Constraint-Mouse
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  FormValidator::Lite::Constraint::Mouse:
    file: lib/FormValidator/Lite/Constraint/Mouse.pm
    version: '0.05'
requires:
  FormValidator::Lite: '0.10'
  Mouse: '0.90'
  Mouse::Util::TypeConstraints: '0'
  perl: '5.008003'
resources:
  bugtracker: https://github.com/hideo55/FormValidator-Lite-Constraint-Mouse/issues
  homepage: https://github.com/hideo55/FormValidator-Lite-Constraint-Mouse
  repository: git://github.com/hideo55/FormValidator-Lite-Constraint-Mouse.git
version: '0.05'
x_contributors:
  - 'Hiroyuki Akabane <hirobanex@gmail.com>'
  - 'hideo55 <hide.o.j55@gmail.com>'
